### PR TITLE
use request URL as default action

### PR DESCRIPTION
**Pull request by plicease**
This lets you test forms with no action or action set to = "".  All browsers that I have tested submit to the same page.

### CODE REVIEW

**Comment by zoffixznet** [comment]
Thanks a lot! Merged and version 1.002001 released on CPAN: https://metacpan.org/release/ZOFFIX/Test-Mojo-Role-SubmitForm-1.002001

**Comment by plicease** [comment]
Thanks!

Weirdly I don't see the new version on metacpan, even though it has been a couple of days.  I do see it on search.cpan.org.

**Comment by zoffixznet** [comment]
Thanks for noticing! I reviewed my emails from PAUSE and I see the update actually failed due to lock timeout. I'll reupload once I get home.

**Comment by zoffixznet** [comment]
I re-uploaded and this time indexing went through fine: https://metacpan.org/release/Test-Mojo-Role-SubmitForm

**Pull request merged**
